name: MD to JSON converter
run-name: Convert MD to JSON 🚀
on: [push]

jobs:
  convert-to-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run script
      run: |
        python mdtojson.py

    - name: display files
      run: |
        ls -a
      
    - name: Upload file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: json-artifact
        path: ./